---
title: "Human Impacts Task"
output: html_notebook
---

```{r setup, include=TRUE, echo=TRUE, message = FALSE}
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(here)
library(C50)
library(caret)
source(here::here("01_tidy", "tidy_human_impacts.r"))
source(here::here("02_analysis", "helpers.R"))
```


```{r }
human_impacts_split <- split_data(data        = human_impacts_derived,
                                  split_ratio = 0.70,
                                  seed        = 123)

```

### Raw Variables
```{r variable}
raw_variables                         <- c("left_transferred_energy", 
                                           "right_transferred_energy", 
                                           "left_gas", 
                                           "right_gas", 
                                           "left_gas_level", 
                                           "right_gas_level",
                                           "left_human_factor", 
                                           "right_human_factor",
                                           "left_human_factor_level", 
                                           "right_human_factor_level",
                                           "left_temperature", 
                                           "right_temperature", 
                                           "left_absorbed_energy", 
                                           "right_absorbed_energy", 
                                           "left_ice", 
                                           "right_ice")

transfer_exact_variables              <- c("transfer", 
                                           "left_transferred_energy", 
                                           "right_transferred_energy", 
                                           "transfer_correct")
     
temperature_exact_variables           <- c("temperature", 
                                           "left_temperature", 
                                           "right_temperature", 
                                           "temperature_correct")

absorption_exact_variables            <- c("absorption", 
                                           "left_absorbed_energy", 
                                           "right_absorbed_energy", 
                                           "absorption_correct")
     
ice_exact_variables                   <- c("ice", 
                                           "left_ice", 
                                           "right_ice", 
                                           "ice_correct")
     
molecule_concentration_exact_variables <- c("molecule_concentration", 
                                           "left_gas", 
                                           "right_gas", 
                                           "left_gas_level", 
                                           "right_gas_level", 
                                           "molecule_concentration_correct")

human_activity_concentration_exact_variables <- c("human_activity_concentration", 
                                           "left_human_factor",
                                           "right_human_factor", 
                                           "left_human_factor_level", 
                                           "right_human_factor_level", 
                                           "human_activity_concentration_correct")

human_activity_molecule_exact_variables <- c("human_activity_molecule", 
                                           "left_human_factor",
                                           "right_human_factor", 
                                           "left_human_factor", 
                                           "right_human_factor", 
                                           "human_activity_molecule_correct")


all_exact_variables                   <- c("left_transferred_energy", 
                                           "right_transferred_energy", 
                                           "left_gas", 
                                           "right_gas", 
                                           "left_gas_level", 
                                           "right_gas_level",
                                           "left_human_factor", 
                                           "right_human_factor",
                                           "left_human_factor_level", 
                                           "right_human_factor_level",
                                           "left_temperature", 
                                           "right_temperature", 
                                           "left_absorbed_energy", 
                                           "right_absorbed_energy", 
                                           "left_ice", 
                                           "right_ice", 
                                           "transfer_correct", 
                                           "temperature_correct", 
                                           "absorption_correct", 
                                           "ice_correct", 
                                           "molecule_concentration_correct", 
                                           "human_activity_concentration_correct", 
                                           "human_activity_molecule_correct", 
                                           "transfer", 
                                           "temperature", 
                                           "absorption", 
                                           "ice", 
                                           "molecule_concentration", 
                                           "human_activity_concentration", 
                                           "human_activity_molecule")
```

### Transfer
```{r transfer-raw}
dt_transfer <- C5.0(x = as.data.frame(human_impacts_split$data[[1]][,raw_variables]), 
                    y = human_impacts_split$data[[1]]$transfer, 
                    trials = 3)
```

```{r transfer-exact}
exact_transfer_summary <- 
  as.data.frame(human_impacts_split$data[[2]][,transfer_exact_variables])

```

```{r predictions-transfer}
predictions_raw <- 
  predict(dt_transfer, 
          newdata = as.data.frame(human_impacts_split$data[[2]][,raw_variables]), 
          type = "class")
confusionMatrix(predictions_raw, 
                reference = human_impacts_split$data[[2]]$transfer)
confusionMatrix(data = exact_transfer_summary$transfer_correct, 
                reference = exact_transfer_summary$transfer)
```

### Temperature
```{r temperature-raw}
dt_temperature <- C5.0(x = as.data.frame(human_impacts_split$data[[1]][,raw_variables]), 
                    y = human_impacts_split$data[[1]]$temperature, 
                    trials = 3)
```

```{r temperature-exact}
exact_temperature_summary <- 
  as.data.frame(human_impacts_split$data[[2]][,temperature_exact_variables])

```

```{r predictions-temperature}
predictions_raw <- 
  predict(dt_temperature, 
          newdata = as.data.frame(human_impacts_split$data[[2]][,raw_variables]), 
          type = "class")
confusionMatrix(predictions_raw, 
                reference = human_impacts_split$data[[2]]$temperature)
confusionMatrix(data = exact_temperature_summary$temperature_correct, 
                reference = exact_temperature_summary$temperature)
```


### Absorption
```{r absorption-raw}
dt_absorption <- C5.0(x = as.data.frame(human_impacts_split$data[[1]][,raw_variables]), 
                    y = human_impacts_split$data[[1]]$absorption, 
                    trials = 3)
```

```{r absorption-exact}
exact_absorption_summary <- 
  as.data.frame(human_impacts_split$data[[2]][,absorption_exact_variables])

```

```{r predictions-absorption}
predictions_raw <- 
  predict(dt_absorption, 
          newdata = as.data.frame(human_impacts_split$data[[2]][,raw_variables]), 
          type = "class")
confusionMatrix(predictions_raw, 
                reference = human_impacts_split$data[[2]]$absorption)
confusionMatrix(data = exact_absorption_summary$absorption_correct, 
                reference = exact_absorption_summary$absorption)
```


### Ice
```{r ice-raw}
dt_ice <- C5.0(x = as.data.frame(human_impacts_split$data[[1]][,raw_variables]), 
                    y = human_impacts_split$data[[1]]$ice, 
                    trials = 3)
```

```{r ice-exact}
exact_ice_summary <- 
  as.data.frame(human_impacts_split$data[[2]][,ice_exact_variables])

```

```{r predictions-ice}
predictions_raw <- 
  predict(dt_ice, 
          newdata = as.data.frame(human_impacts_split$data[[2]][,raw_variables]), 
          type = "class")
confusionMatrix(predictions_raw, 
                reference = human_impacts_split$data[[2]]$ice)
confusionMatrix(data = exact_ice_summary$ice_correct, 
                reference = exact_ice_summary$ice)
```


### Molecule Concentration
```{r molecule_concentration-raw}
dt_molecule_concentration <- C5.0(x = as.data.frame(human_impacts_split$data[[1]][,raw_variables]), 
                    y = human_impacts_split$data[[1]]$molecule_concentration, 
                    trials = 3)
```

```{r molecule_concentration-exact}
exact_molecule_concentration_summary <- 
  as.data.frame(human_impacts_split$data[[2]][,molecule_concentration_exact_variables])

```

```{r predictions-molecule_concentration}
predictions_raw <- 
  predict(dt_molecule_concentration, 
          newdata = as.data.frame(human_impacts_split$data[[2]][,raw_variables]), 
          type = "class")
confusionMatrix(predictions_raw, 
                reference = human_impacts_split$data[[2]]$molecule_concentration)
confusionMatrix(data = exact_molecule_concentration_summary$molecule_concentration_correct, 
                reference = exact_molecule_concentration_summary$molecule_concentration)
```


### Human Activity Concentration
```{r human_activity_concentration-raw}
dt_human_activity_concentration <- 
  C5.0(x = as.data.frame(human_impacts_split$data[[1]][,raw_variables]), 
       y = human_impacts_split$data[[1]]$human_activity_concentration, 
                    trials = 3)
```

```{r human_activity_concentration-exact}
exact_human_activity_concentration_summary <- 
  as.data.frame(human_impacts_split$data[[2]][,human_activity_concentration_exact_variables])

```

```{r predictions-human_activity_concentration}
predictions_raw <- 
  predict(dt_absorption, 
          newdata = as.data.frame(human_impacts_split$data[[2]][,raw_variables]), 
          type = "class")
confusionMatrix(predictions_raw, 
                reference = human_impacts_split$data[[2]]$human_activity_concentration)
confusionMatrix(data = exact_human_activity_concentration_summary$human_activity_concentration_correct, 
                reference = exact_human_activity_concentration_summary$human_activity_concentration)
```


### Human Activity Molecule
```{r human_activity_molecule-raw}
dt_human_activity_molecule <- C5.0(x = as.data.frame(human_impacts_split$data[[1]][,raw_variables]), 
                    y = human_impacts_split$data[[1]]$human_activity_molecule, 
                    trials = 3)
```

```{r human_activity_molecule-exact}
exact_human_activity_molecule_summary <- 
  as.data.frame(human_impacts_split$data[[2]][,human_activity_molecule_exact_variables])

```

```{r predictions-human_activity_molecule}
predictions_raw <- 
  predict(dt_human_activity_molecule, 
          newdata = as.data.frame(human_impacts_split$data[[2]][,raw_variables]), 
          type = "class")
confusionMatrix(predictions_raw, 
                reference = human_impacts_split$data[[2]]$human_activity_molecule)
confusionMatrix(data = exact_human_activity_molecule_summary$human_activity_molecule_correct, 
                reference = exact_human_activity_molecule_summary$human_activity_molecule)
```



### All
```{r all-raw}
dt_all <- C5.0(x = as.data.frame(human_impacts_split$data[[1]][,raw_variables]), 
                    y = human_impacts_split$data[[1]]$all_correct, 
                    trials = 3)
```

```{r all-exact}
exact_all_summary <- 
  as.data.frame(human_impacts_split$data[[2]][,all_exact_variables])

```

```{r predictions-all}
predictions_raw <- 
  predict(dt_all, 
          newdata = as.data.frame(human_impacts_split$data[[2]][,raw_variables]), 
          type = "class")
confusionMatrix(predictions_raw, 
                reference = human_impacts_split$data[[2]]$all_correct)
confusionMatrix(data = exact_all_summary$all_correct, 
                reference = exact_all_summary$all_correct)
```
